In [153]:
import numpy as np
import matplotlib.pyplot as plt

In [154]:
lst = [i for i in range(10)]

In [155]:
np.array(lst)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
lst = [[i, i**2, i**3] for i in range(10)]

In [157]:
np.array(lst)

array([[  0,   0,   0],
       [  1,   1,   1],
       [  2,   4,   8],
       [  3,   9,  27],
       [  4,  16,  64],
       [  5,  25, 125],
       [  6,  36, 216],
       [  7,  49, 343],
       [  8,  64, 512],
       [  9,  81, 729]])

In [158]:
np.arange(0, 28, 4)

array([ 0,  4,  8, 12, 16, 20, 24])

In [159]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [160]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
np.linspace(-1, 1, 20)

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [162]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.random.rand(5, 3)[0][2]*100

44.8007502773918

In [164]:
arr = np.random.randint(5, 10, 50)

In [165]:
arr_e = np.random.randint(1, 100, 50)

In [166]:
arr * 5

array([25, 25, 40, 40, 45, 40, 25, 25, 35, 35, 30, 30, 25, 40, 35, 40, 25,
       30, 35, 25, 40, 30, 45, 45, 35, 45, 45, 30, 45, 35, 40, 45, 25, 35,
       40, 30, 35, 45, 35, 45, 35, 40, 30, 30, 25, 35, 45, 35, 25, 35])

In [167]:
prod = arr * arr_e

In [168]:
prod = np.sqrt(np.sqrt(prod))

In [169]:
prod[3:10] = 999
prod

array([  4.68069464,   3.27472217,   5.16559078, 999.        ,
       999.        , 999.        , 999.        , 999.        ,
       999.        , 999.        ,   4.82057051,   4.87326217,
         3.91531732,   4.88187982,   4.52701906,   3.83365863,
         4.52701906,   3.46410162,   3.86867284,   2.99069756,
         4.64119157,   4.92429805,   2.59002006,   5.44963162,
         2.64575131,   4.65116197,   5.00997014,   4.82057051,
         5.130779  ,   3.86867284,   2.63214803,   4.08696625,
         4.14434121,   4.25891502,   3.41495297,   3.9842826 ,
         3.60020574,   4.15134773,   3.63713576,   3.61617157,
         4.28139029,   3.64232057,   3.86000835,   4.31911543,
         2.23606798,   4.99599519,   5.46348086,   3.0274001 ,
         2.65914795,   4.96768813])

In [170]:
copy = prod.copy()

In [171]:
copy

array([  4.68069464,   3.27472217,   5.16559078, 999.        ,
       999.        , 999.        , 999.        , 999.        ,
       999.        , 999.        ,   4.82057051,   4.87326217,
         3.91531732,   4.88187982,   4.52701906,   3.83365863,
         4.52701906,   3.46410162,   3.86867284,   2.99069756,
         4.64119157,   4.92429805,   2.59002006,   5.44963162,
         2.64575131,   4.65116197,   5.00997014,   4.82057051,
         5.130779  ,   3.86867284,   2.63214803,   4.08696625,
         4.14434121,   4.25891502,   3.41495297,   3.9842826 ,
         3.60020574,   4.15134773,   3.63713576,   3.61617157,
         4.28139029,   3.64232057,   3.86000835,   4.31911543,
         2.23606798,   4.99599519,   5.46348086,   3.0274001 ,
         2.65914795,   4.96768813])

In [172]:
arr2d = np.array([[i, i**2, i**3] for i in range(10)])

In [184]:
arr2d[:,2]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])